pipeline {
    agent any

    tools {nodejs "nodejs-18"}

    environment {
        PATH='/usr/local/bin:/usr/bin:/bin'
    }

    stages {
        stage ('NPM Setup') {
            steps {
                updateGitlabCommitStatus name: 'build', state: 'pending'
                sh 'npm install'
            }
        }

        stage ('Build') {
            steps {
                sh 'npm run ng build --prod'
                sh 'cd dist/frontend && ls'
            }
        }
    }
        post {
            success {
                updateGitlabCommitStatus name: 'build', state: 'success'
            }
            failure {
                updateGitlabCommitStatus name: 'build', state: 'failed'
            }
        }
}
